#!/bin/sh

INCLUDES="includes/"

FT_PRINTF_TESTER_DIR="ft_printf_tester"
FT_PRINT_TESTER_C="ft_printf_tester.c"
NAME="ft_printf_test"

if [ -z "$1" ] || [ "$1" != "b" ]; then
	ARG="m"
else
	ARG=$1
fi

cd ..
make re > /dev/null
cc -Wall -Wextra -Werror -g3 -I $INCLUDES $FT_PRINTF_TESTER_DIR/$FT_PRINT_TESTER_C -L. -lftprintf -o $NAME
valgrind -q --leak-check=full --track-origins=yes --show-leak-kinds=all --track-fds=yes --trace-children=yes ./$NAME $ARG
rm ./$NAME
make fclean > /dev/null
cd $FT_PRINTF_TESTER_DIR
